$SAutodiscoverHostname = "autodiscover.contoso.com" #Hostname Autodiscover. e.g. autodiscover.contoso.com
$SOutlookHostname = "mail.contoso.com" #Hostname Mail. e.g. mail.contoso.com oder outlook.contoso.com
$SExchangeProductKey = "XXXXX-XXXXX-XXXXX-XXXXX-XXXXX" #The Exchange Product Key with -
$SCertFile = "C:\certfs\cert.pfx" #autodiscover cert full path
$SCertPassword = "XXXXX" #autodiscover cert password in cleartext
$SCertFile2 = "H:\exchangeserverauth.pfx"
$SCertPassword2 = "XXXXX"
$SCertEXServices = "*.contoso.com"
#ExcLogPath = "D:\"
